name: GitHub Classroom Workflow

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  checks: write
  actions: read
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    name: Autograding
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build all modules
        run: ./gradlew build --no-daemon

      - name: Test Assignment 01
        run: ./gradlew :01-basic:test --no-daemon
        if: always()

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/build/test-results/**/*.xml

      - name: Run autograding
        uses: education/autograding@v1
        id: autograder
        if: always()
        continue-on-error: true

      - name: Generate autograding report
        uses: education/autograding-grading-reporter@v1
        if: steps.autograder.outputs.runners != ''
        with:
          runners: ${{ steps.autograder.outputs.runners }}
